/* The following code was generated by JFlex 1.4.3 on 4/14/12 11:34 AM */

package org.minijava.scanner;

import java_cup.sym;
import java_cup.runtime.*;
import org.minijava.throwables.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 4/14/12 11:34 AM from the specification file
 * <tt>minijava.jflex</tt>
 */
public final class Scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\2\0\1\3\22\0\1\3\1\43\4\0\1\44"+
    "\1\0\1\46\1\47\1\7\1\40\1\51\1\41\1\36\1\6\1\4"+
    "\11\2\1\0\1\50\1\45\1\42\3\0\22\1\1\34\7\1\1\54"+
    "\1\0\1\55\1\0\1\5\1\0\1\17\1\22\1\15\1\26\1\11"+
    "\1\37\1\33\1\31\1\23\2\1\1\16\1\27\1\14\1\25\1\21"+
    "\1\1\1\10\1\20\1\12\1\13\1\24\1\32\1\30\1\35\1\1"+
    "\1\52\1\0\1\53\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\3\1\1\1\5"+
    "\16\2\1\6\1\2\1\7\1\10\1\11\1\12\1\1"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\2\0\14\2\1\24\6\2\1\25\1\26\2\0"+
    "\5\2\1\27\5\2\1\30\6\2\1\26\1\0\1\2"+
    "\1\31\1\2\1\32\1\33\5\2\1\34\1\35\6\2"+
    "\1\36\4\2\1\37\2\2\1\40\1\41\1\2\1\42"+
    "\1\43\1\44\1\2\1\45\1\2\1\46\1\47\13\0"+
    "\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\56\0\346\0\56"+
    "\0\u0114\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256"+
    "\0\u0284\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\56\0\u0398"+
    "\0\56\0\56\0\56\0\56\0\u03c6\0\56\0\56\0\56"+
    "\0\56\0\56\0\56\0\56\0\56\0\56\0\u03f4\0\u0422"+
    "\0\u0450\0\u047e\0\u04ac\0\u04da\0\u0508\0\u0536\0\u0564\0\u0592"+
    "\0\u05c0\0\u05ee\0\u061c\0\u064a\0\134\0\u0678\0\u06a6\0\u06d4"+
    "\0\u0702\0\u0730\0\u075e\0\56\0\u078c\0\u07ba\0\u07e8\0\u0816"+
    "\0\u0844\0\u0872\0\u08a0\0\u08ce\0\134\0\u08fc\0\u092a\0\u0958"+
    "\0\u0986\0\u09b4\0\134\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a"+
    "\0\u0ac8\0\56\0\u0af6\0\u0b24\0\134\0\u0b52\0\134\0\134"+
    "\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\134\0\134\0\u0c66"+
    "\0\u0c94\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c\0\134\0\u0d7a\0\u0da8"+
    "\0\u0dd6\0\u0e04\0\134\0\u0e32\0\u0e60\0\134\0\134\0\u0e8e"+
    "\0\134\0\134\0\134\0\u0ebc\0\134\0\u0eea\0\134\0\134"+
    "\0\u0f18\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe\0\u102c\0\u105a"+
    "\0\u1088\0\u10b6\0\u10e4\0\56";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\12\1\13\1\3\1\14\1\15\1\16\1\3"+
    "\1\17\1\20\1\21\1\22\1\23\2\3\1\24\2\3"+
    "\1\25\1\3\1\26\1\3\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\57\0\2\3\1\0\2\3"+
    "\2\0\26\3\1\0\1\3\20\0\1\4\1\0\1\4"+
    "\54\0\1\5\60\0\1\47\1\50\47\0\2\3\1\0"+
    "\2\3\2\0\1\3\1\51\24\3\1\0\1\3\17\0"+
    "\2\3\1\0\2\3\2\0\6\3\1\52\11\3\1\53"+
    "\5\3\1\0\1\3\17\0\2\3\1\0\2\3\2\0"+
    "\1\54\20\3\1\55\4\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\1\3\1\56\24\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\6\3\1\57\17\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\1\3"+
    "\1\60\24\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\2\3\1\61\23\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\3\3\1\62\22\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\15\3\1\63\10\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\4\3"+
    "\1\64\21\3\1\0\1\65\17\0\2\3\1\0\2\3"+
    "\2\0\15\3\1\66\10\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\7\3\1\67\16\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\21\3\1\70\4\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\2\3"+
    "\1\71\22\3\1\72\1\0\1\3\17\0\2\3\1\0"+
    "\2\3\2\0\7\3\1\73\16\3\1\0\1\3\62\0"+
    "\1\74\11\0\7\75\1\0\46\75\7\76\1\77\46\76"+
    "\1\0\2\3\1\0\2\3\2\0\2\3\1\100\23\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\10\3"+
    "\1\101\15\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\2\3\1\102\23\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\3\3\1\103\22\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\13\3\1\104\12\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\22\3"+
    "\1\105\3\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\7\3\1\106\16\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\4\3\1\107\21\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\7\3\1\110\16\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\12\3"+
    "\1\111\13\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\15\3\1\112\10\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\2\3\1\113\23\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\13\3\1\114\12\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\13\3"+
    "\1\115\12\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\13\3\1\116\12\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\1\117\25\3\1\0\1\3\17\0"+
    "\2\3\1\0\2\3\2\0\10\3\1\120\15\3\1\0"+
    "\1\3\17\0\2\3\1\0\2\3\2\0\6\3\1\121"+
    "\17\3\1\0\1\3\21\0\1\122\52\0\7\76\1\123"+
    "\46\76\6\0\1\122\1\77\47\0\2\3\1\0\2\3"+
    "\2\0\3\3\1\124\22\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\1\3\1\125\24\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\1\3\1\126\24\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\1\3"+
    "\1\127\24\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\10\3\1\130\15\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\10\3\1\131\15\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\23\3\1\132\2\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\2\3"+
    "\1\133\23\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\6\3\1\134\17\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\6\3\1\135\17\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\16\3\1\136\7\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\4\3"+
    "\1\137\21\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\6\3\1\140\17\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\13\3\1\141\12\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\2\3\1\142\23\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\10\3"+
    "\1\143\15\3\1\0\1\3\16\0\6\76\1\122\1\123"+
    "\46\76\1\0\2\3\1\0\2\3\2\0\1\144\25\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\4\3"+
    "\1\145\21\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\10\3\1\146\15\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\2\3\1\147\23\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\13\3\1\150\12\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\13\3"+
    "\1\151\12\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\1\3\1\152\24\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\1\3\1\153\24\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\4\3\1\154\21\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\1\3"+
    "\1\155\24\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\1\3\1\156\24\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\4\3\1\157\21\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\16\3\1\160\7\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\21\3"+
    "\1\161\4\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\5\3\1\162\20\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\5\3\1\163\20\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\7\3\1\164\16\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\23\3"+
    "\1\165\2\3\1\0\1\3\17\0\2\3\1\0\2\3"+
    "\2\0\17\3\1\166\6\3\1\0\1\3\17\0\2\3"+
    "\1\0\2\3\2\0\10\3\1\167\15\3\1\0\1\3"+
    "\17\0\2\3\1\0\2\3\2\0\4\3\1\170\21\3"+
    "\1\0\1\3\17\0\2\3\1\0\2\3\2\0\26\3"+
    "\1\171\1\3\43\0\1\172\43\0\1\173\54\0\1\174"+
    "\101\0\1\175\40\0\1\176\44\0\1\177\70\0\1\200"+
    "\46\0\1\201\53\0\1\202\61\0\1\203\53\0\1\204"+
    "\41\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4370];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\1\11\16\1\1\11"+
    "\1\1\4\11\1\1\11\11\2\0\23\1\1\11\1\1"+
    "\2\0\22\1\1\11\1\0\45\1\13\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[132];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  // note that these Symbol constructors are abusing the Symbol
  // interface to use Symbol's left and right fields as line and column
  // fields instead
  
  private Symbol symbol(int type) {
    return new Symbol(type, yyline+1, yycolumn+1);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline+1, yycolumn+1, value);
  }
	
  // print out a symbol (aka token) nicely
	public String symbolToString(Symbol symbol) {
		return Sym.toString(symbol);
	}
  


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 128) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, MiniJavaException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { return symbol(Sym.DEL_LPAREN);
          }
        case 41: break;
        case 17: 
          { return symbol(Sym.DEL_RBRACE);
          }
        case 42: break;
        case 38: 
          { return symbol(Sym.WORD_EXTENDS);
          }
        case 43: break;
        case 40: 
          { return symbol(Sym.WORD_PRINTLN);
          }
        case 44: break;
        case 29: 
          { return symbol(Sym.WORD_MAIN);
          }
        case 45: break;
        case 28: 
          { return symbol(Sym.WORD_VOID);
          }
        case 46: break;
        case 36: 
          { return symbol(Sym.WORD_PUBLIC);
          }
        case 47: break;
        case 15: 
          { return symbol(Sym.DEL_COMMA);
          }
        case 48: break;
        case 31: 
          { return symbol(Sym.COND_WHILE);
          }
        case 49: break;
        case 9: 
          { return symbol(Sym.OP_EQUAL);
          }
        case 50: break;
        case 30: 
          { return symbol(Sym.WORD_CLASS);
          }
        case 51: break;
        case 26: 
          { return symbol(Sym.BOOL_TRUE);
          }
        case 52: break;
        case 27: 
          { return symbol(Sym.WORD_THIS);
          }
        case 53: break;
        case 34: 
          { return symbol(Sym.WORD_LENGTH);
          }
        case 54: break;
        case 39: 
          { return symbol(Sym.TYPE_BOOL);
          }
        case 55: break;
        case 19: 
          { return symbol(Sym.DEL_RBRACK);
          }
        case 56: break;
        case 8: 
          { return symbol(Sym.OP_MINUS);
          }
        case 57: break;
        case 13: 
          { return symbol(Sym.DEL_RPAREN);
          }
        case 58: break;
        case 3: 
          { return symbol(Sym.INTEGER_LITERAL, yytext());
          }
        case 59: break;
        case 1: 
          { throw new LexicalException("Invalid Character: '"+yytext()+"'");
          }
        case 60: break;
        case 2: 
          { return symbol(Sym.IDENTIFIER, yytext());
          }
        case 61: break;
        case 10: 
          { return symbol(Sym.OP_NOT);
          }
        case 62: break;
        case 21: 
          { return symbol(Sym.OP_AND);
          }
        case 63: break;
        case 6: 
          { return symbol(Sym.DEL_DOT);
          }
        case 64: break;
        case 33: 
          { return symbol(Sym.WORD_RETURN);
          }
        case 65: break;
        case 16: 
          { return symbol(Sym.DEL_LBRACE);
          }
        case 66: break;
        case 32: 
          { return symbol(Sym.BOOL_FALSE);
          }
        case 67: break;
        case 37: 
          { return symbol(Sym.TYPE_STRING);
          }
        case 68: break;
        case 20: 
          { return symbol(Sym.COND_IF);
          }
        case 69: break;
        case 35: 
          { return symbol(Sym.WORD_STATIC);
          }
        case 70: break;
        case 22: 
          { /* Ignore os comentários */
          }
        case 71: break;
        case 4: 
          { /* Ignore os espaços em branco */
          }
        case 72: break;
        case 25: 
          { return symbol(Sym.COND_ELSE);
          }
        case 73: break;
        case 7: 
          { return symbol(Sym.OP_PLUS);
          }
        case 74: break;
        case 14: 
          { return symbol(Sym.DEL_SEMICOLON);
          }
        case 75: break;
        case 24: 
          { return symbol(Sym.TYPE_INT);
          }
        case 76: break;
        case 11: 
          { return symbol(Sym.OP_LT);
          }
        case 77: break;
        case 18: 
          { return symbol(Sym.DEL_LBRACK);
          }
        case 78: break;
        case 23: 
          { return symbol(Sym.WORD_NEW);
          }
        case 79: break;
        case 5: 
          { return symbol(Sym.OP_MULT);
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
